version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      # Group all non-major npm dependencies together
      npm-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      npm-dependencies-prod:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      # Group all GitHub Actions dependencies together
      github-actions:
        patterns:
          - "*"
