name: Create Issue

on:
  workflow_dispatch:

jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh issue create \
            --title "Temporary Issue Title" \
            --body "This is a temporary issue body." \
            --label "bug"
